POST http://localhost:3000/requestOpenai
Content-Type: application/json

{
  "prompt": "A flying bird"
}

###

POST http://localhost:3000/getSurroundingNodes
Content-Type: application/json

{
  "location": {
    "latitude": 60.184720,
    "longitude": 24.832324
  }
}

POST http://localhost:3000/getPointsByBoundingBox
Content-Type: application/json

{
  "south": 60.184720,
  "west": 24.832324,
  "north": 60.184720,
  "east": 24.832324
}
